[workspace]

members = [
    "usn-parser",
    "usn-change-journal",
]

resolver = "2"

[profile.release]
opt-level = "z"     # Optimize for size
lto = true          # Enable Link Time Optimization
panic = "abort"