[package]
name = "usn-parser-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
usn-journal-rs = {path = "../../usn-journal-rs"}
clap = { version = "4.5", features = ["derive"] }
log = "0.4" 
anyhow = "1.0"
chrono = "0.4"

[[bin]]
name = "usn-parser"
path = "src/main.rs"

