name: Publish to crates.io

on:
  push:
    tags:
      - 'v*'  # Trigger on tags matching v*, like v1.0.0

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish to crates.io
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: x86_64-pc-windows-msvc
      
      - name: Verify package
        run: cargo package
      
      - name: Login to crates.io
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
      
      - name: Publish to crates.io
        run: cargo publish
